### ISSUE TITLE
Auto-shape discovery isn't working

### ISSUE THREAD

**Issue by derekssmith** [naveego/plugin-pub-mssql#9]
While working with the MSSQL plugin lately I noticed that the auto-discovery has stopped working.  For a little while the *Add Discovered Shapes* button was being populated with the tables and views, but the past few days it doesn't seem to be working.  

![image](https://user-images.githubusercontent.com/14862993/47537787-a6283f80-d87c-11e8-90ff-8fb3f57aff03.png)

### Chrome Console Errors
![image](https://user-images.githubusercontent.com/14862993/47537847-fb645100-d87c-11e8-8420-030a58a909aa.png)

![image](https://user-images.githubusercontent.com/14862993/47537887-2353b480-d87d-11e8-990e-99dd8a202ed8.png)

**Comment by SteveRuble** [comment]
Yes.
________________________________
